# Generated by Django 5.1 on 2024-10-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_pledge_supporter_project_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='movie_synopsis',
        ),
        migrations.AddField(
            model_name='project',
            name='director',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='genres',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
