# Generated by Django 5.1 on 2024-09-21 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_pledge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='anoymous',
            new_name='anonymous',
        ),
    ]
