# Generated by Django 5.1 on 2024-10-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_goal_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='goal_deadline',
            field=models.DateField(),
        ),
    ]
