# Generated by Django 4.2.5 on 2024-10-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_goal_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='goal_deadline',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
