# Generated by Django 5.1 on 2024-10-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_goal_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='genres',
            field=models.CharField(max_length=100),
        ),
    ]
