# Generated by Django 5.1 on 2024-10-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='goal_deadline',
            field=models.DateTimeField(),
        ),
    ]
